# Generated by Django 2.2.4 on 2024-01-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mar_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_fname', models.CharField(max_length=45)),
                ('c_lname', models.CharField(max_length=45)),
                ('c_email', models.EmailField(max_length=254)),
                ('c_subject', models.CharField(max_length=45)),
                ('c_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
